on: [push]

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: README the RSS
      uses: kohrongying/readme-the-rss@v1
      with:
        feed_url: "https://www.brewinstallbuzzwords.com/index.xml"





  
